# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster
WORKDIR /cb_flask

COPY ../python/config/requirements.txt ./config/requirements.txt
RUN pip3 install -r ./config/requirements.txt

# ../
COPY ../python ./python

EXPOSE 5001

CMD [ "flask", "run", "--host=0.0.0.0", "--port=5001"]